### ISSUE TITLE
annotate_query() not effect

### ISSUE THREAD

**Issue by tornado404** [ariarijp/redash-queryable-csv-query-runner#1]
My program run failed in Redash 9.0.0.beta, which shows "bool can not be str".
query_runner.run_query() call annotate_query() as query_str, however redash-queryable-csv-query-runner return bool.
I suggest  that annotate_query() should be deleted and use parent class.

**Comment by ariarijp** [comment]
@hateTornado Thank you for your help. #2 will solve it.
